eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false # 这两个false，标志服务端
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/

server:
  port: 9003
