server:
  port: 8004

spring:
  application:
    name: microservicecloud-provider

eureka:
  client:
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/,http://eureka9003.com:9003/eureka/
  instance:
    instance-id: provider8004
    prefer-ip-address: true