server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/,http://eureka9003.com:9003/eureka/
  instance:
    instance-id: provider8002 # 自定义服务名称信息
    prefer-ip-address: true # 访问路径可以显示IP地址

spring:
  application:
    name: microservicecloud-provider # 微服务的名字
  zipkin:
    base-url: http://localhost:9411/  # zipkin服务器的地址
    sender:
      type: web  # 设置使用http的方式传输数据
  sleuth:
    sampler:
      probability: 1  # 设置抽样采集为100%，默认为0.1，即10%